//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.SuccessResource", typeof(SuccessResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   if a: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0000 {
            get {
                return ResourceManager.GetString("Success0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a:
        ///  pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0001 {
            get {
                return ResourceManager.GetString("Success0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif a: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0002 {
            get {
                return ResourceManager.GetString("Success0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a:
        ///  pass
        ///elif a:
        ///  pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0003 {
            get {
                return ResourceManager.GetString("Success0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///else: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0004 {
            get {
                return ResourceManager.GetString("Success0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif a: pass
        ///else: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0005 {
            get {
                return ResourceManager.GetString("Success0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif b: pass
        ///elif c: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0006 {
            get {
                return ResourceManager.GetString("Success0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif b: pass
        ///elif c: pass
        ///else: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0007 {
            get {
                return ResourceManager.GetString("Success0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a:
        ///  if b: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0008 {
            get {
                return ResourceManager.GetString("Success0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a:
        ///  if b: pass
        ///else:
        ///  if c: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0009 {
            get {
                return ResourceManager.GetString("Success0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   while a:
        ///  pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0100 {
            get {
                return ResourceManager.GetString("Success0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   while a: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0101 {
            get {
                return ResourceManager.GetString("Success0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   while a:
        ///  pass
        ///else:
        ///  pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0102 {
            get {
                return ResourceManager.GetString("Success0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   while a:
        ///  while b:
        ///    pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success0103 {
            get {
                return ResourceManager.GetString("Success0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 + 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4000 {
            get {
                return ResourceManager.GetString("Success4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 + a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4001 {
            get {
                return ResourceManager.GetString("Success4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a + 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4002 {
            get {
                return ResourceManager.GetString("Success4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a + a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4003 {
            get {
                return ResourceManager.GetString("Success4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 - 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4010 {
            get {
                return ResourceManager.GetString("Success4010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 - a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4011 {
            get {
                return ResourceManager.GetString("Success4011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a - 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4012 {
            get {
                return ResourceManager.GetString("Success4012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a - a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4013 {
            get {
                return ResourceManager.GetString("Success4013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 * 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4020 {
            get {
                return ResourceManager.GetString("Success4020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 * a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4021 {
            get {
                return ResourceManager.GetString("Success4021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a * 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4022 {
            get {
                return ResourceManager.GetString("Success4022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a * a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4023 {
            get {
                return ResourceManager.GetString("Success4023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 / 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4030 {
            get {
                return ResourceManager.GetString("Success4030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 / a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4031 {
            get {
                return ResourceManager.GetString("Success4031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a / 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4032 {
            get {
                return ResourceManager.GetString("Success4032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a / a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4033 {
            get {
                return ResourceManager.GetString("Success4033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 // 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4040 {
            get {
                return ResourceManager.GetString("Success4040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 // a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4041 {
            get {
                return ResourceManager.GetString("Success4041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a // 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4042 {
            get {
                return ResourceManager.GetString("Success4042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a // a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4043 {
            get {
                return ResourceManager.GetString("Success4043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ~ 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4050 {
            get {
                return ResourceManager.GetString("Success4050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ~ a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4051 {
            get {
                return ResourceManager.GetString("Success4051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ~ 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4052 {
            get {
                return ResourceManager.GetString("Success4052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ~ a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4053 {
            get {
                return ResourceManager.GetString("Success4053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 % 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4060 {
            get {
                return ResourceManager.GetString("Success4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 % a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4061 {
            get {
                return ResourceManager.GetString("Success4061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a % 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4062 {
            get {
                return ResourceManager.GetString("Success4062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a % a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4063 {
            get {
                return ResourceManager.GetString("Success4063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &amp; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4070 {
            get {
                return ResourceManager.GetString("Success4070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &amp; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4071 {
            get {
                return ResourceManager.GetString("Success4071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &amp; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4072 {
            get {
                return ResourceManager.GetString("Success4072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &amp; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4073 {
            get {
                return ResourceManager.GetString("Success4073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 | 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4080 {
            get {
                return ResourceManager.GetString("Success4080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 | a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4081 {
            get {
                return ResourceManager.GetString("Success4081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a | 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4082 {
            get {
                return ResourceManager.GetString("Success4082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a | a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4083 {
            get {
                return ResourceManager.GetString("Success4083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ^ 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4090 {
            get {
                return ResourceManager.GetString("Success4090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ^ a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4091 {
            get {
                return ResourceManager.GetString("Success4091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ^ 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4092 {
            get {
                return ResourceManager.GetString("Success4092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ^ a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4093 {
            get {
                return ResourceManager.GetString("Success4093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &lt; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40a0 {
            get {
                return ResourceManager.GetString("Success40a0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &lt; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40a1 {
            get {
                return ResourceManager.GetString("Success40a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &lt; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40a2 {
            get {
                return ResourceManager.GetString("Success40a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &lt; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40a3 {
            get {
                return ResourceManager.GetString("Success40a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &gt; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40b0 {
            get {
                return ResourceManager.GetString("Success40b0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &gt; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40b1 {
            get {
                return ResourceManager.GetString("Success40b1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &gt; 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40b2 {
            get {
                return ResourceManager.GetString("Success40b2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &gt; a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40b3 {
            get {
                return ResourceManager.GetString("Success40b3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 . a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40c1 {
            get {
                return ResourceManager.GetString("Success40c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a . a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40c3 {
            get {
                return ResourceManager.GetString("Success40c3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 = 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40d0 {
            get {
                return ResourceManager.GetString("Success40d0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 = a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40d1 {
            get {
                return ResourceManager.GetString("Success40d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a = 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40d2 {
            get {
                return ResourceManager.GetString("Success40d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a = a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success40d3 {
            get {
                return ResourceManager.GetString("Success40d3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 is 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4100 {
            get {
                return ResourceManager.GetString("Success4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 is a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4101 {
            get {
                return ResourceManager.GetString("Success4101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a is 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4102 {
            get {
                return ResourceManager.GetString("Success4102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a is a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4103 {
            get {
                return ResourceManager.GetString("Success4103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 !is 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4110 {
            get {
                return ResourceManager.GetString("Success4110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 !is a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4111 {
            get {
                return ResourceManager.GetString("Success4111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a !is 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4112 {
            get {
                return ResourceManager.GetString("Success4112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a !is a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4113 {
            get {
                return ResourceManager.GetString("Success4113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 is not 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4120 {
            get {
                return ResourceManager.GetString("Success4120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 is not a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4121 {
            get {
                return ResourceManager.GetString("Success4121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a is not 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4122 {
            get {
                return ResourceManager.GetString("Success4122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a is not a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4123 {
            get {
                return ResourceManager.GetString("Success4123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 and 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4130 {
            get {
                return ResourceManager.GetString("Success4130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 and a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4131 {
            get {
                return ResourceManager.GetString("Success4131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a and 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4132 {
            get {
                return ResourceManager.GetString("Success4132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a and a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4133 {
            get {
                return ResourceManager.GetString("Success4133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 or 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4140 {
            get {
                return ResourceManager.GetString("Success4140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 or a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4141 {
            get {
                return ResourceManager.GetString("Success4141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a or 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4142 {
            get {
                return ResourceManager.GetString("Success4142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a or a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4143 {
            get {
                return ResourceManager.GetString("Success4143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 **= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4200 {
            get {
                return ResourceManager.GetString("Success4200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 **= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4201 {
            get {
                return ResourceManager.GetString("Success4201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a **= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4202 {
            get {
                return ResourceManager.GetString("Success4202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a **= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4203 {
            get {
                return ResourceManager.GetString("Success4203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 *= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4210 {
            get {
                return ResourceManager.GetString("Success4210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 *= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4211 {
            get {
                return ResourceManager.GetString("Success4211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a *= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4212 {
            get {
                return ResourceManager.GetString("Success4212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a *= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4213 {
            get {
                return ResourceManager.GetString("Success4213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 /= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4220 {
            get {
                return ResourceManager.GetString("Success4220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 /= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4221 {
            get {
                return ResourceManager.GetString("Success4221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a /= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4222 {
            get {
                return ResourceManager.GetString("Success4222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a /= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4223 {
            get {
                return ResourceManager.GetString("Success4223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 //= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4230 {
            get {
                return ResourceManager.GetString("Success4230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 //= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4231 {
            get {
                return ResourceManager.GetString("Success4231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a //= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4232 {
            get {
                return ResourceManager.GetString("Success4232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a //= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4233 {
            get {
                return ResourceManager.GetString("Success4233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 %= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4240 {
            get {
                return ResourceManager.GetString("Success4240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 %= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4241 {
            get {
                return ResourceManager.GetString("Success4241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a %= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4242 {
            get {
                return ResourceManager.GetString("Success4242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a %= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4243 {
            get {
                return ResourceManager.GetString("Success4243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 += 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4250 {
            get {
                return ResourceManager.GetString("Success4250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 += a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4251 {
            get {
                return ResourceManager.GetString("Success4251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a += 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4252 {
            get {
                return ResourceManager.GetString("Success4252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a += a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4253 {
            get {
                return ResourceManager.GetString("Success4253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 -= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4260 {
            get {
                return ResourceManager.GetString("Success4260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 -= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4261 {
            get {
                return ResourceManager.GetString("Success4261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a -= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4262 {
            get {
                return ResourceManager.GetString("Success4262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a -= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4263 {
            get {
                return ResourceManager.GetString("Success4263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ~= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4270 {
            get {
                return ResourceManager.GetString("Success4270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ~= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4271 {
            get {
                return ResourceManager.GetString("Success4271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ~= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4272 {
            get {
                return ResourceManager.GetString("Success4272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ~= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4273 {
            get {
                return ResourceManager.GetString("Success4273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 |= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4280 {
            get {
                return ResourceManager.GetString("Success4280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 |= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4281 {
            get {
                return ResourceManager.GetString("Success4281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a |= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4282 {
            get {
                return ResourceManager.GetString("Success4282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a |= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4283 {
            get {
                return ResourceManager.GetString("Success4283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &amp;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4290 {
            get {
                return ResourceManager.GetString("Success4290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &amp;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4291 {
            get {
                return ResourceManager.GetString("Success4291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &amp;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4292 {
            get {
                return ResourceManager.GetString("Success4292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &amp;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4293 {
            get {
                return ResourceManager.GetString("Success4293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ^= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42a0 {
            get {
                return ResourceManager.GetString("Success42a0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ^= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42a1 {
            get {
                return ResourceManager.GetString("Success42a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ^= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42a2 {
            get {
                return ResourceManager.GetString("Success42a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ^= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42a3 {
            get {
                return ResourceManager.GetString("Success42a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &lt;&lt;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42b0 {
            get {
                return ResourceManager.GetString("Success42b0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &lt;&lt;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42b1 {
            get {
                return ResourceManager.GetString("Success42b1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &lt;&lt;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42b2 {
            get {
                return ResourceManager.GetString("Success42b2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &lt;&lt;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42b3 {
            get {
                return ResourceManager.GetString("Success42b3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &gt;&gt;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42c0 {
            get {
                return ResourceManager.GetString("Success42c0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 &gt;&gt;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42c1 {
            get {
                return ResourceManager.GetString("Success42c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &gt;&gt;= 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42c2 {
            get {
                return ResourceManager.GetString("Success42c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a &gt;&gt;= a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success42c3 {
            get {
                return ResourceManager.GetString("Success42c3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1++ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4300 {
            get {
                return ResourceManager.GetString("Success4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a++ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4301 {
            get {
                return ResourceManager.GetString("Success4301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1-- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4310 {
            get {
                return ResourceManager.GetString("Success4310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a-- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4311 {
            get {
                return ResourceManager.GetString("Success4311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ref 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4320 {
            get {
                return ResourceManager.GetString("Success4320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ref a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4321 {
            get {
                return ResourceManager.GetString("Success4321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ++1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4330 {
            get {
                return ResourceManager.GetString("Success4330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ++a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4331 {
            get {
                return ResourceManager.GetString("Success4331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4340 {
            get {
                return ResourceManager.GetString("Success4340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4341 {
            get {
                return ResourceManager.GetString("Success4341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4350 {
            get {
                return ResourceManager.GetString("Success4350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4351 {
            get {
                return ResourceManager.GetString("Success4351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4360 {
            get {
                return ResourceManager.GetString("Success4360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4361 {
            get {
                return ResourceManager.GetString("Success4361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4370 {
            get {
                return ResourceManager.GetString("Success4370", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4371 {
            get {
                return ResourceManager.GetString("Success4371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   !1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4380 {
            get {
                return ResourceManager.GetString("Success4380", resourceCulture);
            }
        }
        
        /// <summary>
        ///   !a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4381 {
            get {
                return ResourceManager.GetString("Success4381", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4390 {
            get {
                return ResourceManager.GetString("Success4390", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4391 {
            get {
                return ResourceManager.GetString("Success4391", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ? 1 : 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4400 {
            get {
                return ResourceManager.GetString("Success4400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ? 1 : a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4401 {
            get {
                return ResourceManager.GetString("Success4401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ? a : 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4402 {
            get {
                return ResourceManager.GetString("Success4402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ? a : a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4403 {
            get {
                return ResourceManager.GetString("Success4403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ? 1 : 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4404 {
            get {
                return ResourceManager.GetString("Success4404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ? 1 : a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4405 {
            get {
                return ResourceManager.GetString("Success4405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ? a : 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4406 {
            get {
                return ResourceManager.GetString("Success4406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a ? a : a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4407 {
            get {
                return ResourceManager.GetString("Success4407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 if 1 else 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4410 {
            get {
                return ResourceManager.GetString("Success4410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 if 1 else a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4411 {
            get {
                return ResourceManager.GetString("Success4411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 if a else 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4412 {
            get {
                return ResourceManager.GetString("Success4412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 if a else a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4413 {
            get {
                return ResourceManager.GetString("Success4413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a if 1 else 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4414 {
            get {
                return ResourceManager.GetString("Success4414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a if 1 else a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4415 {
            get {
                return ResourceManager.GetString("Success4415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a if a else 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4416 {
            get {
                return ResourceManager.GetString("Success4416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a if a else a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4417 {
            get {
                return ResourceManager.GetString("Success4417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4500 {
            get {
                return ResourceManager.GetString("Success4500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4501 {
            get {
                return ResourceManager.GetString("Success4501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4502 {
            get {
                return ResourceManager.GetString("Success4502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(1, 1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4503 {
            get {
                return ResourceManager.GetString("Success4503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(1, a) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4504 {
            get {
                return ResourceManager.GetString("Success4504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a, 1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4505 {
            get {
                return ResourceManager.GetString("Success4505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a, a) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4506 {
            get {
                return ResourceManager.GetString("Success4506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a, a, a) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4507 {
            get {
                return ResourceManager.GetString("Success4507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a: 1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4510 {
            get {
                return ResourceManager.GetString("Success4510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a(a: a) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Success4511 {
            get {
                return ResourceManager.GetString("Success4511", resourceCulture);
            }
        }
    }
}
