//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   if:
        /// pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0000 {
            get {
                return ResourceManager.GetString("SyntaxError0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if if:
        ///  pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0001 {
            get {
                return ResourceManager.GetString("SyntaxError0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0003 {
            get {
                return ResourceManager.GetString("SyntaxError0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if if: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0004 {
            get {
                return ResourceManager.GetString("SyntaxError0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   elif a:
        /// pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0005 {
            get {
                return ResourceManager.GetString("SyntaxError0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a:
        ///elif a:
        /// pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0006 {
            get {
                return ResourceManager.GetString("SyntaxError0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if: pass
        ///elif a: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0007 {
            get {
                return ResourceManager.GetString("SyntaxError0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if:
        /// pass
        ///elif a: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0008 {
            get {
                return ResourceManager.GetString("SyntaxError0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError0009 {
            get {
                return ResourceManager.GetString("SyntaxError0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if: pass
        ///elif a: pass に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError000a {
            get {
                return ResourceManager.GetString("SyntaxError000a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if:
        /// pass
        ///else: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError000b {
            get {
                return ResourceManager.GetString("SyntaxError000b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if: pass
        ///else: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SyntaxError000c {
            get {
                return ResourceManager.GetString("SyntaxError000c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedEOF0001 {
            get {
                return ResourceManager.GetString("UnexpectedEOF0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if a: pass
        ///elif a: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedEOF0002 {
            get {
                return ResourceManager.GetString("UnexpectedEOF0002", resourceCulture);
            }
        }
    }
}
